version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        links:
            - fpm
        volumes:
            - ./:/var/www/html
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/html
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 8089:15672
        # volumes:
        #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
